apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: activemq
  name: activemq-deployment
  namespace: semaforr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
      - image: webcenter/activemq:5.14.3
        imagePullPolicy: IfNotPresent
        name: activemq
        ports:
        - containerPort: 8161
          protocol: TCP
        - containerPort: 1883
          protocol: TCP
        - containerPort: 5672
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: activemq
  namespace: semaforr
spec:
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: activemq
  type: ClusterIP
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: message-broker
  namespace: semaforr
data:
  ACTIVEMQ_AMQP_URL: amqp://activemq:5672
  ACTIVEMQ_MQTT_URL: tcp://activemq:1883
  MQ_CLIENT: activemq
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: message-broker
  namespace: semaforr
data:
  ACTIVE_MQ_PASSWORD: YWRtaW4=
  ACTIVE_MQ_USERNAME: YWRtaW4=
