apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-hub
  namespace: semaforr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-reader
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: get-deployments
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployment-reader
subjects:
- kind: ServiceAccount
  name: event-hub
  namespace: semaforr
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: event-hub
  name: event-hub
  namespace: semaforr
spec:
  replicas: 3
  selector:
    matchLabels:
      run: event-hub
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: event-hub
    spec:
      serviceAccountName: event-hub
      containers:
      - image: semaforr/kube-proxy
        imagePullPolicy: Always
        name: kube-proxy
        ports:
        - containerPort: 8001
      - image: semaforr/event-hub
        imagePullPolicy: IfNotPresent
        name: event-hub
        env:
        - name: SERVICE_REGISTRY_CLIENT
          value: kubernetes
        envFrom:
          - configMapRef:
              name: message-broker
          - secretRef:
              name: message-broker
        